[2024-08-25 19:20:23,532: INFO: main: Welocome to our custom logging.]
[2024-08-25 19:20:31,340: INFO: main: Welocome to our custom logging.]
[2024-08-25 19:20:37,385: INFO: main: Welocome to our custom logging.]
[2024-08-25 19:20:52,446: INFO: main: Welcome to our custom logging.]
[2024-08-27 20:09:51,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:09:51,935: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:09:51,939: INFO: common: created directory at: artifacts]
[2024-08-27 20:09:51,947: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:09:51,960: INFO: 2166426223: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:10:13,927: INFO: 2166426223: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:14:08,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:14:08,147: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:14:08,155: INFO: common: created directory at: artifacts]
[2024-08-27 20:14:08,158: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:14:08,163: INFO: 2166426223: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:14:31,118: INFO: 2166426223: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:17:56,681: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:17:56,681: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:17:56,691: INFO: common: created directory at: artifacts]
[2024-08-27 20:17:56,696: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:17:56,699: INFO: 2166426223: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:18:18,475: INFO: 2166426223: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:18:40,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:18:40,162: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:18:40,167: INFO: common: created directory at: artifacts]
[2024-08-27 20:18:40,173: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:18:40,177: INFO: 661843391: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:19:01,918: INFO: 661843391: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:32:52,953: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:32:52,958: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:32:52,966: INFO: common: created directory at: artifacts]
[2024-08-27 20:32:52,971: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:32:52,975: INFO: 3073340465: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:33:15,005: INFO: 3073340465: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:47:21,634: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:47:21,645: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:47:21,655: INFO: common: created directory at: artifacts]
[2024-08-27 20:47:21,664: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:47:21,671: INFO: 3073340465: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:47:43,634: INFO: 3073340465: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 20:50:53,427: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 20:50:53,434: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 20:50:53,444: INFO: common: created directory at: artifacts]
[2024-08-27 20:50:53,448: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 20:50:53,456: INFO: 1286384308: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion]
[2024-08-27 21:00:14,303: INFO: 1286384308: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion]
[2024-08-27 21:16:29,720: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 21:16:29,725: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 21:16:29,729: INFO: common: created directory at: artifacts]
[2024-08-27 21:16:29,732: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 21:16:29,732: INFO: 1286384308: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 21:24:41,576: INFO: 1286384308: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 22:25:41,649: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-27 22:25:41,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 22:25:41,660: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 22:25:41,661: INFO: common: created directory at: artifacts]
[2024-08-27 22:25:41,662: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 22:25:41,662: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 22:31:58,069: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 22:32:11,481: ERROR: main: [Errno 28] No space left on device]
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 10, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_01_data_ingestion.py", line 19, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\data_ingestion.py", line 46, in extract_zip_file
    zip_ref.extractall(unzip_path)
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\zipfile.py", line 1701, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\zipfile.py", line 1756, in _extract_member
    shutil.copyfileobj(source, target)
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\shutil.py", line 200, in copyfileobj
    fdst_write(buf)
OSError: [Errno 28] No space left on device
[2024-08-27 22:45:34,948: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-27 22:45:34,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 22:45:34,948: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 22:45:34,948: INFO: common: created directory at: artifacts]
[2024-08-27 22:45:34,948: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 22:45:34,948: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 22:53:15,319: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-27 22:53:15,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-27 22:53:15,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-27 22:53:15,343: INFO: common: created directory at: artifacts]
[2024-08-27 22:53:15,343: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-27 22:53:15,343: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 22:59:56,932: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-27 23:00:22,603: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x=============x]
[2024-08-28 02:08:53,950: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 02:08:53,951: ERROR: main: [Errno 2] No such file or directory: '..\\config\\config.yaml']
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 13, in main
    config = ConfigurationManager()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\utils\common.py", line 37, in read_yaml
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\utils\common.py", line 30, in read_yaml
    with open(path_to_yaml) as yaml_file:
         ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '..\\config\\config.yaml'
[2024-08-28 02:10:00,343: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 02:10:00,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 02:10:00,351: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 02:10:00,358: INFO: common: created directory at: artifacts]
[2024-08-28 02:10:00,360: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 02:10:01,238: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 02:10:01,706: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 02:10:01,937: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-28 19:26:44,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:26:44,976: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:26:44,981: INFO: common: created directory at: artifacts]
[2024-08-28 19:26:44,989: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:26:47,229: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:28:00,067: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:28:00,074: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:28:00,079: INFO: common: created directory at: artifacts]
[2024-08-28 19:28:00,083: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:28:00,864: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:28:33,403: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:28:33,417: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:28:33,426: INFO: common: created directory at: artifacts]
[2024-08-28 19:28:33,430: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:28:34,314: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:35:03,333: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:35:03,342: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:35:03,347: INFO: common: created directory at: artifacts]
[2024-08-28 19:35:03,354: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:35:04,208: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:35:46,908: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:35:46,913: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:35:46,914: INFO: common: created directory at: artifacts]
[2024-08-28 19:35:46,920: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:35:47,431: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:36:18,362: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:36:18,368: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:36:18,372: INFO: common: created directory at: artifacts]
[2024-08-28 19:36:18,376: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:36:19,033: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:37:07,129: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:37:07,145: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:37:07,154: INFO: common: created directory at: artifacts]
[2024-08-28 19:38:00,550: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:38:00,556: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:38:00,556: INFO: common: created directory at: artifacts]
[2024-08-28 19:38:00,567: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:38:01,165: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:39:17,691: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:39:17,698: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:39:17,705: INFO: common: created directory at: artifacts]
[2024-08-28 19:39:17,708: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:39:18,281: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:40:44,857: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:40:44,858: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:40:44,867: INFO: common: created directory at: artifacts]
[2024-08-28 19:40:44,871: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:43:43,178: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:43:43,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:43:43,195: INFO: common: created directory at: artifacts]
[2024-08-28 19:43:43,195: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:44:46,559: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:44:46,565: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:44:46,568: INFO: common: created directory at: artifacts]
[2024-08-28 19:44:46,573: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:44:47,161: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:45:20,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:45:20,108: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:45:20,115: INFO: common: created directory at: artifacts]
[2024-08-28 19:45:20,120: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:45:20,841: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:45:34,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:45:34,078: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:45:34,082: INFO: common: created directory at: artifacts]
[2024-08-28 19:45:34,086: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:45:34,790: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:46:03,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:46:03,548: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:46:03,554: INFO: common: created directory at: artifacts]
[2024-08-28 19:46:03,558: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:46:04,072: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:46:27,276: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:46:27,283: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:46:27,283: INFO: common: created directory at: artifacts]
[2024-08-28 19:46:27,289: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:46:27,822: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:49:49,938: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:49:49,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:49:49,954: INFO: common: created directory at: artifacts]
[2024-08-28 19:49:49,957: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:49:51,037: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:50:57,086: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:50:57,091: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:50:57,097: INFO: common: created directory at: artifacts]
[2024-08-28 19:50:57,102: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:50:57,839: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:51:40,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:51:40,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:51:40,564: INFO: common: created directory at: artifacts]
[2024-08-28 19:51:40,572: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:51:41,196: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:53:03,096: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:53:03,105: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:53:03,109: INFO: common: created directory at: artifacts]
[2024-08-28 19:53:03,116: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:53:03,943: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:55:21,524: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:55:21,527: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:55:21,536: INFO: common: created directory at: artifacts]
[2024-08-28 19:55:21,540: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:55:22,262: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 19:55:58,472: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 19:55:58,484: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 19:55:58,488: INFO: common: created directory at: artifacts]
[2024-08-28 19:55:58,494: INFO: common: created directory at: artifacts\training]
[2024-08-28 19:55:59,337: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:01:33,101: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:01:33,112: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:01:33,121: INFO: common: created directory at: artifacts]
[2024-08-28 20:01:33,128: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:01:33,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:04:56,921: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:04:56,929: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:04:56,934: INFO: common: created directory at: artifacts]
[2024-08-28 20:04:56,938: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:04:58,041: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:05:13,480: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:05:13,484: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:05:13,495: INFO: common: created directory at: artifacts]
[2024-08-28 20:05:13,499: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:05:14,269: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:07:38,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:07:38,470: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:07:38,478: INFO: common: created directory at: artifacts]
[2024-08-28 20:07:38,483: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:07:39,051: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:08:49,200: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:08:49,204: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:08:49,204: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:08:49,204: INFO: common: created directory at: artifacts]
[2024-08-28 20:08:49,213: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:08:50,535: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:08:51,386: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:08:51,836: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-28 20:09:06,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:09:06,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:09:06,372: INFO: common: created directory at: artifacts]
[2024-08-28 20:09:06,376: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:09:07,328: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:09:56,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:09:56,126: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:09:56,133: INFO: common: created directory at: artifacts]
[2024-08-28 20:09:56,133: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:09:57,001: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:15:11,848: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:15:11,851: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:15:11,855: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:15:11,858: INFO: common: created directory at: artifacts]
[2024-08-28 20:15:11,859: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:15:12,694: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:15:13,359: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:15:13,808: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-28 20:15:23,516: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:15:23,516: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:15:23,526: INFO: common: created directory at: artifacts]
[2024-08-28 20:15:23,528: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:15:24,284: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:16:40,237: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:16:40,251: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:16:40,255: INFO: common: created directory at: artifacts]
[2024-08-28 20:16:40,262: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:16:41,372: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:18:30,099: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:18:30,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:18:30,109: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:18:30,115: INFO: common: created directory at: artifacts]
[2024-08-28 20:18:30,118: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:18:30,930: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:18:31,428: ERROR: main: `keras.optimizers.legacy` is not supported in Keras 3. When using `tf.keras`, to continue using a `tf.keras.optimizers.legacy` optimizer, you can install the `tf_keras` package (Keras 2) and set the environment variable `TF_USE_LEGACY_KERAS=True` to configure TensorFlow to use `tf_keras` when accessing `tf.keras`.]
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.update_base_model()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\prepare_base_model.py", line 53, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\prepare_base_model.py", line 40, in _prepare_full_model
    optimizer = tf.keras.optimizers.legacy.SGD(learning_rate=learning_rate),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\__init__.py", line 115, in __init__
    raise ImportError(
ImportError: `keras.optimizers.legacy` is not supported in Keras 3. When using `tf.keras`, to continue using a `tf.keras.optimizers.legacy` optimizer, you can install the `tf_keras` package (Keras 2) and set the environment variable `TF_USE_LEGACY_KERAS=True` to configure TensorFlow to use `tf_keras` when accessing `tf.keras`.
[2024-08-28 20:21:42,333: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:21:42,340: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:21:42,341: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:21:42,341: INFO: common: created directory at: artifacts]
[2024-08-28 20:21:42,346: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:21:42,347: ERROR: main: 'PrepareBaseModelConfig' object has no attribute 'params_weights']
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.get_base_model()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\prepare_base_model.py", line 17, in get_base_model
    weights=self.config.params_weights,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrepareBaseModelConfig' object has no attribute 'params_weights'
[2024-08-28 20:22:25,520: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:22:25,525: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:22:25,538: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:22:25,545: INFO: common: created directory at: artifacts]
[2024-08-28 20:22:25,565: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:22:26,593: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:22:27,185: ERROR: main: `keras.optimizers.legacy` is not supported in Keras 3. When using `tf.keras`, to continue using a `tf.keras.optimizers.legacy` optimizer, you can install the `tf_keras` package (Keras 2) and set the environment variable `TF_USE_LEGACY_KERAS=True` to configure TensorFlow to use `tf_keras` when accessing `tf.keras`.]
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 21, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 19, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.update_base_model()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\prepare_base_model.py", line 53, in update_base_model
    self.full_model = self._prepare_full_model(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\prepare_base_model.py", line 40, in _prepare_full_model
    optimizer = tf.keras.optimizers.legacy.SGD(learning_rate=learning_rate),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\optimizers\__init__.py", line 115, in __init__
    raise ImportError(
ImportError: `keras.optimizers.legacy` is not supported in Keras 3. When using `tf.keras`, to continue using a `tf.keras.optimizers.legacy` optimizer, you can install the `tf_keras` package (Keras 2) and set the environment variable `TF_USE_LEGACY_KERAS=True` to configure TensorFlow to use `tf_keras` when accessing `tf.keras`.
[2024-08-28 20:23:38,951: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:23:38,956: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:23:38,966: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:23:38,967: INFO: common: created directory at: artifacts]
[2024-08-28 20:23:38,967: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:23:40,033: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:23:40,818: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:23:41,704: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-28 20:28:58,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:28:58,280: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:28:58,287: INFO: common: created directory at: artifacts]
[2024-08-28 20:28:58,290: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:28:59,171: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:29:32,909: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:29:32,913: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:29:32,916: INFO: common: created directory at: artifacts]
[2024-08-28 20:29:32,923: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:29:33,512: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:37:33,913: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 20:37:33,916: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:37:33,919: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:37:33,920: INFO: common: created directory at: artifacts]
[2024-08-28 20:37:33,921: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 20:37:34,595: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:37:35,333: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 20:37:36,095: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-28 20:50:17,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:50:17,828: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:50:17,836: INFO: common: created directory at: artifacts]
[2024-08-28 20:50:17,838: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:50:18,380: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 20:50:29,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 20:50:29,469: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 20:50:29,473: INFO: common: created directory at: artifacts]
[2024-08-28 20:50:29,477: INFO: common: created directory at: artifacts\training]
[2024-08-28 20:50:29,976: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 22:18:04,287: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 22:18:04,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 22:18:04,302: INFO: common: created directory at: artifacts]
[2024-08-28 22:18:04,304: INFO: common: created directory at: artifacts\training]
[2024-08-28 22:18:04,916: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 22:20:46,369: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 22:20:46,380: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 22:20:46,388: INFO: common: created directory at: artifacts]
[2024-08-28 22:20:46,393: INFO: common: created directory at: artifacts\training]
[2024-08-28 22:20:47,247: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 22:25:26,270: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-28 22:25:26,274: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 22:25:26,276: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 22:25:26,278: INFO: common: created directory at: artifacts]
[2024-08-28 22:25:26,279: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-28 22:25:27,147: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 22:25:27,918: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-28 22:25:28,315: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-28 22:26:57,755: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 22:26:57,760: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 22:26:57,764: INFO: common: created directory at: artifacts]
[2024-08-28 22:26:57,767: INFO: common: created directory at: artifacts\training]
[2024-08-28 22:26:58,813: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-28 22:39:53,619: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-28 22:39:53,626: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-28 22:39:53,641: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-28 22:39:53,657: INFO: common: created directory at: artifacts]
[2024-08-28 22:39:53,672: INFO: common: created directory at: artifacts\training]
[2024-08-28 22:39:54,535: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-29 20:29:48,409: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 20:29:48,462: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 20:29:48,465: INFO: common: created directory at: artifacts]
[2024-08-29 20:29:48,473: INFO: common: created directory at: artifacts\training]
[2024-08-29 20:29:50,216: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-29 21:11:51,889: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-29 23:05:26,688: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-08-29 23:05:26,708: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 23:05:26,740: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 23:05:26,743: INFO: common: created directory at: artifacts]
[2024-08-29 23:05:28,753: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-29 23:16:33,622: INFO: common: json file saved at: scores.json]
[2024-08-29 23:16:56,552: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x=============x]
[2024-08-29 23:21:43,280: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-08-29 23:21:43,286: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 23:21:43,294: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 23:21:43,296: INFO: common: created directory at: artifacts]
[2024-08-29 23:21:44,141: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-29 23:32:28,071: INFO: common: json file saved at: scores.json]
[2024-08-29 23:32:29,494: INFO: helpers: Accessing as saadan1234]
[2024-08-29 23:32:30,828: INFO: helpers: Initialized MLflow to track repo "saadan1234/Kidney-Tumor-Classification"]
[2024-08-29 23:32:30,833: INFO: helpers: Repository saadan1234/Kidney-Tumor-Classification initialized!]
[2024-08-29 23:33:42,784: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x=============x]
[2024-08-29 23:41:01,751: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-08-29 23:41:01,760: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-29 23:41:01,769: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-29 23:41:01,776: INFO: common: created directory at: artifacts]
[2024-08-29 23:41:02,426: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-29 23:54:26,048: INFO: common: json file saved at: scores.json]
[2024-08-29 23:54:28,622: INFO: helpers: Accessing as saadan1234]
[2024-08-29 23:54:32,112: INFO: helpers: Initialized MLflow to track repo "saadan1234/Kidney-Tumor-Classification"]
[2024-08-29 23:54:32,122: INFO: helpers: Repository saadan1234/Kidney-Tumor-Classification initialized!]
[2024-08-29 23:56:05,626: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x=============x]
[2024-08-30 14:52:17,634: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-30 14:52:17,644: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 14:52:17,656: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 14:52:17,657: INFO: common: created directory at: artifacts]
[2024-08-30 14:52:17,659: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 14:52:17,660: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 14:59:43,882: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 15:00:17,140: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x=============x]
[2024-08-30 15:00:17,142: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-30 15:00:17,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:00:17,153: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:00:17,155: INFO: common: created directory at: artifacts]
[2024-08-30 15:00:17,163: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 15:00:18,546: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 15:00:18,887: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 15:00:19,090: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-30 15:00:19,091: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 15:00:19,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:00:19,098: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:00:19,101: INFO: common: created directory at: artifacts]
[2024-08-30 15:00:19,102: INFO: common: created directory at: artifacts\training]
[2024-08-30 15:00:19,406: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 15:00:19,442: ERROR: main: Must provide at least one structure]
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 34, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_03_model_training.py", line 20, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\model_training.py", line 72, in train
    self.model.fit(
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\tree\optree_impl.py", line 76, in map_structure
    raise ValueError("Must provide at least one structure")
ValueError: Must provide at least one structure
[2024-08-30 15:16:35,581: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-30 15:16:35,589: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:16:35,605: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:16:35,608: INFO: common: created directory at: artifacts]
[2024-08-30 15:16:35,609: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 15:16:35,611: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 15:24:25,190: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 15:24:54,028: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x=============x]
[2024-08-30 15:24:54,029: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-30 15:24:54,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:24:54,039: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:24:54,044: INFO: common: created directory at: artifacts]
[2024-08-30 15:24:54,045: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 15:24:54,708: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 15:24:54,928: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 15:24:55,057: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-30 15:24:55,058: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 15:24:55,061: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:24:55,064: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:24:55,065: INFO: common: created directory at: artifacts]
[2024-08-30 15:24:55,073: INFO: common: created directory at: artifacts\training]
[2024-08-30 15:24:55,333: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 15:24:55,339: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\data_ingestion']
Traceback (most recent call last):
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\main.py", line 34, in <module>
    obj.main()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_03_model_training.py", line 20, in main
    raise e
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training.train_valid_generator()
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\components\model_training.py", line 33, in train_valid_generator
    self.valid_generator = valid_datagenerator.flow_from_directory(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 1138, in flow_from_directory
    return DirectoryIterator(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\preprocessing\image.py", line 453, in __init__
    for subdir in sorted(os.listdir(directory)):
                         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\data_ingestion'
[2024-08-30 15:34:25,027: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-30 15:34:25,027: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:34:25,041: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:34:25,047: INFO: common: created directory at: artifacts]
[2024-08-30 15:34:25,047: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 15:34:25,047: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 15:37:03,438: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-30 15:37:03,438: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:37:03,438: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:37:03,438: INFO: common: created directory at: artifacts]
[2024-08-30 15:37:03,448: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 15:37:03,449: INFO: data_ingestion: File artifacts/data_ingestion/data.zip already exists. Skipping download.]
[2024-08-30 15:37:18,492: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x=============x]
[2024-08-30 15:37:18,492: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-30 15:37:18,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:37:18,510: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:37:18,511: INFO: common: created directory at: artifacts]
[2024-08-30 15:37:18,513: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 15:37:19,072: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 15:37:19,384: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 15:37:19,625: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-30 15:37:19,626: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 15:37:19,627: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 15:37:19,634: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 15:37:19,635: INFO: common: created directory at: artifacts]
[2024-08-30 15:37:19,636: INFO: common: created directory at: artifacts\training]
[2024-08-30 15:37:19,873: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 16:09:36,011: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 16:09:36,373: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x=============x]
[2024-08-30 16:09:36,373: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-08-30 16:09:36,383: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 16:09:36,390: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 16:09:36,392: INFO: common: created directory at: artifacts]
[2024-08-30 16:09:36,803: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 16:19:51,394: INFO: common: json file saved at: scores.json]
[2024-08-30 16:19:53,295: INFO: helpers: Accessing as saadan1234]
[2024-08-30 16:19:54,827: INFO: helpers: Initialized MLflow to track repo "saadan1234/Kidney-Tumor-Classification"]
[2024-08-30 16:19:54,834: INFO: helpers: Repository saadan1234/Kidney-Tumor-Classification initialized!]
[2024-08-30 16:21:40,084: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x=============x]
[2024-08-30 19:58:16,184: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<]
[2024-08-30 19:58:16,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 19:58:16,203: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 19:58:16,205: INFO: common: created directory at: artifacts]
[2024-08-30 19:58:16,207: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-30 19:58:16,209: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:05:42,026: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1-2Y6sOXk3eLNwpFxXDZCmbSneG39xJie/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-30 20:06:49,986: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x=============x]
[2024-08-30 20:06:49,987: INFO: main: >>>>>> stage Preparing Base Model Stage started <<<<<<]
[2024-08-30 20:06:50,003: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:06:50,069: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:06:50,086: INFO: common: created directory at: artifacts]
[2024-08-30 20:06:50,088: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-30 20:06:54,869: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 20:06:57,161: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 20:06:58,163: INFO: main: >>>>>> stage Preparing Base Model Stage completed <<<<<<

x=============x]
[2024-08-30 20:06:58,174: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 20:06:58,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 20:06:58,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 20:06:58,340: INFO: common: created directory at: artifacts]
[2024-08-30 20:06:58,354: INFO: common: created directory at: artifacts\training]
[2024-08-30 20:07:00,187: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 20:38:07,746: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.146:8080]
[2024-08-30 20:38:07,749: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-30 20:38:20,670: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 20:38:20] "GET / HTTP/1.1" 200 -]
[2024-08-30 20:39:00,176: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-08-30 20:39:00,217: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 20:39:00] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 21:52:56,659: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 21:52:56,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 21:52:56,676: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 21:52:56,694: INFO: common: created directory at: artifacts]
[2024-08-30 21:52:56,703: INFO: common: created directory at: artifacts\training]
[2024-08-30 21:52:57,769: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 22:08:45,588: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 22:08:45,592: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 22:08:45,612: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 22:08:45,614: INFO: common: created directory at: artifacts]
[2024-08-30 22:08:45,619: INFO: common: created directory at: artifacts\training]
[2024-08-30 22:08:46,339: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 22:22:20,442: INFO: main: >>>>>> stage Model Training Stage started <<<<<<]
[2024-08-30 22:22:20,444: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 22:22:20,457: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 22:22:20,458: INFO: common: created directory at: artifacts]
[2024-08-30 22:22:20,459: INFO: common: created directory at: artifacts\training]
[2024-08-30 22:22:21,069: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:08:32,438: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-08-30 23:08:32,647: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x=============x]
[2024-08-30 23:08:32,648: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-08-30 23:08:32,654: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:08:32,658: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:08:32,659: INFO: common: created directory at: artifacts]
[2024-08-30 23:08:33,051: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:19:12,949: INFO: common: json file saved at: scores.json]
[2024-08-30 23:19:12,950: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x=============x]
[2024-08-30 23:22:16,649: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<]
[2024-08-30 23:22:16,649: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-30 23:22:16,649: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-30 23:22:16,649: INFO: common: created directory at: artifacts]
[2024-08-30 23:22:17,065: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:34:33,916: INFO: common: json file saved at: scores.json]
[2024-08-30 23:34:35,017: INFO: helpers: Accessing as saadan1234]
[2024-08-30 23:34:35,923: INFO: helpers: Initialized MLflow to track repo "saadan1234/Kidney-Tumor-Classification"]
[2024-08-30 23:34:35,927: INFO: helpers: Repository saadan1234/Kidney-Tumor-Classification initialized!]
[2024-08-30 23:35:39,527: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x=============x]
[2024-08-30 23:37:39,872: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.146:8080]
[2024-08-30 23:37:39,873: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-30 23:40:32,109: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 23:40:32] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:40:38,514: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-08-30 23:40:38,537: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 23:40:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 23:43:05,900: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 23:43:05] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:43:06,260: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 23:43:06] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:43:13,490: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'model\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-08-30 23:43:13,502: INFO: _internal: 127.0.0.1 - - [30/Aug/2024 23:43:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 23:43:44,293: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.146:8080]
[2024-08-30 23:43:44,293: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-30 23:43:48,886: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:43:48] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:44:01,428: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 14, in predict
    model = load_model(os.path.join("training", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'training\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-08-30 23:44:01,450: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:44:01] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 23:45:31,214: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:45:31] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:45:38,223: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 14, in predict
    imagename = self.filename
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 116, in load_model_from_hdf5
    f = h5py.File(filepath, mode="r")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'training\model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
[2024-08-30 23:45:38,223: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:45:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 23:47:44,618: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.146:8080]
[2024-08-30 23:47:44,618: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-30 23:47:50,279: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:47:50] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:47:58,310: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 12, in predict
    model = self.load_model(self.config.trained_model_path)
            ^^^^^^^^^^^^^^^
AttributeError: 'PredictionPipeline' object has no attribute 'load_model'
[2024-08-30 23:47:58,317: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:47:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 23:48:42,510: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.146:8080]
[2024-08-30 23:48:42,510: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-30 23:48:44,588: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:48:44] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:48:48,759: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dell\miniconda3\envs\kidney\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "c:\Users\dell\Documents\GitHub\Kidney-Tumor-Classification\app.py", line 36, in predictionRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\users\dell\documents\github\kidney-tumor-classification\src\kidneyClassifier\pipeline\prediction.py", line 12, in predict
    model = load_model(self.config.trained_model_path)
                       ^^^^^^^^^^^
AttributeError: 'PredictionPipeline' object has no attribute 'config'
[2024-08-30 23:48:48,777: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:48:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-30 23:49:50,143: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.100.146:8080]
[2024-08-30 23:49:50,143: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-30 23:49:52,143: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:49:52] "GET / HTTP/1.1" 200 -]
[2024-08-30 23:49:55,918: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:49:57,766: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:49:57] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:50:10,100: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:50:11,505: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:50:11] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:50:17,641: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:50:19,054: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:50:19] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:50:27,717: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:50:29,075: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:50:29] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:50:51,133: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:50:52,449: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002296F6C4FE0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-08-30 23:50:52,471: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:50:52] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:51:00,804: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:51:02,175: WARNING: polymorphic_function: 6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002296F6C44A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-08-30 23:51:02,182: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:51:02] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:51:07,214: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:51:08,649: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:51:08] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:51:14,204: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:51:15,420: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:51:15] "POST /predict HTTP/1.1" 200 -]
[2024-08-30 23:51:21,013: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-30 23:51:22,366: INFO: _internal: 192.168.100.146 - - [30/Aug/2024 23:51:22] "POST /predict HTTP/1.1" 200 -]
